sudo: false

language: python

addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev

python:
  - 2.7

before_install:
  - pip install -U pip wheel setuptools

install:
  - pip install numpy nose six matplotlib
  - pip install scipy
  - pip install scikit-image scikit-learn
  - pip install flake8 hacking

script:
  - flake8 apc_od scripts tests
  - nosetests -v -s tests

cache:
  directories:
    - $HOME/.cache/pip
