sudo: false

language: python

addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev

python:
  - 2.7

before_install:
  - pip install -U pip wheel setuptools
  - pip install -U -v numpy scipy

install:
  - pip install -r requirements.txt
  - pip install flake8 nose gdown coveralls

before_script:
  - gdown "https://drive.google.com/uc?id=0B9P1L--7Wd2vWU9QRjdocktoU1U&export=download" -O data/raw_data.tgz
  - (cd data && tar zxf raw_data.tgz && mv raw_data/* .)

script:
  - flake8 apc_od scripts tests
  - nosetests tests --with-coverage --cover-package=apc_od

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false
